plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = 'blamejared'
        url = "https://maven.blamejared.com"
    }
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.tterrag.com" }
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
    maven { url = "https://maven.createmod.net" }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run')
            programArguments.addAll '-mixin.config=tfc.mixins.json', '-mixin.config=create.mixins.json', '-mixin.config=woodencog.mixins.json'
            systemProperty 'mixin.env.remapRefMap', 'true'

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        client2 {
            client()
            gameDirectory = project.file('run2')
            programArguments.addAll '--username', 'Dev###', '--accessToken', '0', '--userType', 'legacy', '--userProperties', '{}', '--clientId', '', '--xuid', ''
            programArguments.addAll '-mixin.config=tfc.mixins.json', '-mixin.config=create.mixins.json', '-mixin.config=woodencog.mixins.json'
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            gameDirectory = project.file('run')
            programArgument '--nogui'
            programArguments.add '-mixin.config=create.mixins.json'
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }


        gameTestServer {
            type = "gameTestServer"
            gameDirectory = project.file('run')
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            gameDirectory = project.file('run')

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "curse.maven:terrafirmacraft-${tfc_project_id}:${tfc_file_id}"
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation "net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}"
    implementation "dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}"
    implementation "com.tterrag.registrate:Registrate:${registrate_version}"

    implementation "curse.maven:createaddition-${createaddition_project_id}:${createaddition_file_id}"
    implementation "curse.maven:create-low-heated-${create_low_heated_project_id}:${create_low_heated_file_id}"
    implementation "curse.maven:more-create-burners-${more_create_burners_project_id}:${more_create_burners_file_id}"

    compileOnly "vazkii.patchouli:Patchouli:${minecraft_version}-${patchouli_version}:api"
    runtimeOnly "vazkii.patchouli:Patchouli:${minecraft_version}-${patchouli_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    implementation "io.github.llamalad7:mixinextras-neoforge:${mixin_extras_version}"
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
}


var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
