org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

mod_version=1.2.15
minecraft_version=1.21.1
neo_version=21.1.220
forgegradle_version=6.0.6
mixingradle_version = 0.7-SNAPSHOT
librarian_version = 1.+
shadow_version = 7.1.0
cursegradle_version = 1.4.0
parchment_version = 2023.06.26

mixin_version = 0.8.5
mixin_extras_version = 0.4.1

create_version = 6.0.10-281
ponder_version = 1.0.82
flywheel_version = 1.0.5
registrate_version = MC1.20-1.3.3
patchouli_version = 92-NEOFORGE
jei_version = 19.9.1.125

mod_group_id=net.chauvedev.woodencog
mod_id=woodencog
mod_name=Wooden Cog
mod_license=MIT
mod_authors=ChauveDev
mod_description=A NeoForge mod that adds wooden cog integration between TerraFirmaCraft and Create

minecraft_version_range=[1.21.1,1.22)
neo_version_range=[21.1.220,)
loader_version_range=[4,)

parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1

tfc_project_id=302973
tfc_file_id=8028557
createaddition_project_id=439890
createaddition_file_id=7518252
create_low_heated_project_id=873945
create_low_heated_file_id=7985006
more_create_burners_project_id=1111030
more_create_burners_file_id=7062699